# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'First' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for First

  target 'First-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'First-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for First-tvOS

  target 'First-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
    pod 'Picker', :path => '../node_modules/react-native-picker'
    
  end

end
